### ISSUE TITLE
[BUG] ApplicationDbContext invalid operation

### ISSUE THREAD

**Issue by Furkan2514** [openbullet/OpenBullet2#91] opened 2021-03-13 11:07 UTC
in all configs i tried, there are to check and ban loop, and i'm sure my proxies and combo is right. also a error appears on console.
![image](https://user-images.githubusercontent.com/40518338/111028089-72c2bd00-8405-11eb-8589-e2ebd72fe92c.png)

**Comment by openbullet** [comment] 2021-03-13 20:49
Version 0.1.2 had a serious issue, please use 0.1.3 and let me know if it's fixed. I edited the title of this issue to point to the second bug you pointed out.

**Comment by Furkan2514** [comment] 2021-03-14 15:34
i'm using 0.1.4 and still same error appearing
![image](https://user-images.githubusercontent.com/40518338/111074434-f3f87d80-84f3-11eb-8f54-9cf27ebe20b2.png)

**Comment by openbullet** [comment] 2021-03-14 15:51
@Furkan2514 if the issue is still open it means it hasn't been solved, no need to confirm that it's still present in other versions. When the issue is closed, in the update right after it you will be able to see if it actually works or not.

**Comment by Furkan2514** [comment] 2021-03-15 10:13
yea but you said "let me know it if its fixed on 0.1.3

**Comment by openbullet** [comment] 2021-03-15 12:14
> 
> 
> yea but you said "let me know it if its fixed on 0.1.3

Read again. I said that related to the other thing you asked for (TO check and ban loop) which is not related to the AppDbContext issue. Then you said "also an error appears in console" so I changed the issue to address the second thing. This is why you should make multiple issues for each separate thing, otherwise it creates confusion ^_^

**Comment by openbullet** [comment] 2021-03-19 16:22
Please when update 0.1.8 is available test this again and let me know if you still get this exception in the console, thank you.

**Comment by Teals53** [comment] 2021-03-21 17:33
still not fixed
![Uploading image.png…]()

**Comment by Furkan2514** [comment] 2021-03-21 20:15
It is fixed for me now. no errors in the console

**Comment by openbullet** [comment] 2021-03-21 20:29
@Teals53 please describe all the steps you took in order to have that bug. Did it involve purging the hits db or did you just start OB2 and started a job?

**Comment by Teals53** [comment] 2021-03-23 09:21
when i start checking its looping ban and when i stop that its giving these errors

**Comment by Teals53** [comment] 2021-03-24 11:54
maybe it is happening if conifg have ban key

**Comment by openbullet** [comment] 2021-03-27 15:23
Please let me know if this issue is still present in 0.1.9

**Comment by Teals53** [comment] 2021-03-27 15:30
let me test

**Comment by openbullet** [comment] 2021-03-27 15:37
> 
> 
> let me test

The fact that it's looping bans has nothing to do with it btw. Read this https://discourse.openbullet.dev/t/comprehensive-guide-to-wordlist-types/435 and make sure the wordlist type of your wordlist matches the one in your config.

Just let me know if the errors in the console saying `InvalidOperationException` are gone so I can close the issue.

**Comment by Teals53** [comment] 2021-03-27 19:45
![image](https://user-images.githubusercontent.com/13446881/112732946-1c4d9680-8f4e-11eb-9256-f1136c15856d.png)
still no clue why its keep happening

**Comment by Teals53** [comment] 2021-03-27 19:54
it can be possible cuz of these lines in wordlist ?

![image](https://user-images.githubusercontent.com/13446881/112733163-59feef00-8f4f-11eb-8ab1-052567aeea2f.png)

talking about weird characters

**Comment by openbullet** [comment] 2021-03-27 19:59
Assuming this issue is fixed, if someone else is experiencing this problem with 0.1.9 please open a new issue.

**Closed** 2021-05-11 17:33 UTC
Labels: bug

**Comment by 212zz** [comment] 2024-06-23 18:03
i think my issue might be related to this
https://github.com/openbullet/OpenBullet2/issues/994
