### ISSUE TITLE
[Bug]: Not able to run Puppeteer in non-headless mode

### ISSUE THREAD

**Issue by ShayMe21** [openbullet/OpenBullet2#669] opened 2022-03-21 05:24 UTC
### Version of the software

0.2.3

### Operating system

MacOS Monterey

### Browser / Native

Chrome 99

### What happened?

The first Puppeteer "Open Browser" Block fails when I untick the "Headless" mode in the Settings.

```
[Executing block Open Browser] ProcessException: PuppeteerSharp.ProcessException: Failed to launch Base! [1998:1998:0321/052153.027888:ERROR:ozone_platform_x11.cc(234)] Missing X server or $DISPLAY
[1998:1998:0321/052153.027974:ERROR:env.cc(225)] The platform failed to initialize.  Exiting.

   at PuppeteerSharp.LauncherBase.State.StartingState.StartCoreAsync(LauncherBase p)
   at PuppeteerSharp.LauncherBase.State.StartingState.StartCoreAsync(LauncherBase p)
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options, Product product)
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options, Product product)
   at PuppeteerExtraSharp.PuppeteerExtra.LaunchAsync(LaunchOptions options)
   at RuriLib.Blocks.Puppeteer.Browser.Methods.PuppeteerOpenBrowser(BotData data)
   at Submission#0.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunSubmissionsAsync(ScriptExecutionState executionState, ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.ScriptStateTaskExtensions.CastAsync[S,T](Task`1 task)
   at RuriLib.Models.Debugger.ConfigDebugger.Run()
```

<img width="554" alt="image" src="https://user-images.githubusercontent.com/14830205/159209019-c5b28bcd-9345-4ed0-b07f-9270685bf608.png">

I am running OB2 using Docker command and in RL Settings, my chrome binary location is set to: `/usr/bin/chromium`

**Comment by openbullet** [comment] 2022-03-21 20:25
Docker containers don't have an X server so it's not possible to render the browser's GUI. The only thing that works is headless. This is not a bug, closing

**Closed by openbullet** 2022-03-21 20:25 UTC
Labels: bug
