### ISSUE TITLE
[REQUEST] OB error - Microsoft.AspNetCore.Server.Kestrel[22]

### ISSUE THREAD

**Issue by e393** [openbullet/OpenBullet2#275] opened 2021-05-24 07:20 UTC
warn: Microsoft.AspNetCore.Server.Kestrel[22]
      As of "05/24/2021 07:16:11 +00:00", the heartbeat has been running for "00:00:01.7538024" which is longer than "00:00:01". This could be caused by thread pool starvation.

**Comment by openbullet** [comment] 2021-05-24 14:01
1. When does it happen?
2. Does it happen consistently?
3. I see it's just a warning, does it affect the usability of the program?
4. Have you modified your values according to this guide? https://discourse.openbullet.dev/t/making-your-openbullet-2-instance-more-stable/2111

**Comment by e393** [comment] 2021-05-24 14:50
1. not really sure couldn't remember when or what i was doing when i saw it
2. not really
3. no
4. I did before but that was days ago since then all values are by default "1000"

**Comment by openbullet** [comment] 2021-05-24 14:52
Since it's just a warning and cannot be consistently reproduced, I'm going to close this for the time being. Reopen if you manage to give me a way to reproduce it and if it breaks the program, otherwise I cannot help with it.

**Closed by openbullet** 2021-05-24 14:52 UTC
Labels: bug
