### ISSUE TITLE
[Bug]: Puppeteer

### ISSUE THREAD

**Issue by marcosms1992** [openbullet/OpenBullet2#1115] opened 2024-09-15 16:01 UTC
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://discourse.openbullet.dev/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/openbullet/OpenBullet2/issues?q=is%3Aissue+is%3Aopen+label%3Abug) *(I've searched it)*.
- [X] I'm using an up to date version of OpenBullet2. We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow OpenBullet's [Code of Conduct](https://docs.openbullet.dev/docs/community-standards).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Find By XPath is not working, it shows this error. NotSupportedException: Specified method is not supported.
Only the latest version shows the error

![image](https://github.com/user-attachments/assets/b1a92f94-8f79-49e5-b6bf-b7f808d5dd50)

### Reproduction steps

Only the latest version shows the error

### What is the current bug behavior?

[Executing block Type Human] NotSupportedException: Specified method is not supported.

### What is the expected correct behavior?

[Executing block Type Human] NotSupportedException: Specified method is not supported.
Only the latest version shows the error

### Version of the client

2.0 Only the latest version shows the error

### Type of client

Web client

### Environment

```markdown
- OS:Windows 
- Virtualization:Web
- Browser:Chrome
```

**Comment by marcosms1992** [comment] 2024-09-15 16:09
![image](https://github.com/user-attachments/assets/2b035536-5a05-4da3-bacc-ec1c2ba1c500)

**Comment by openbullet** [comment] 2024-09-16 05:41
Duplicate of #1070

**Closed** 2024-09-16 05:41 UTC
Labels: bug
