### ISSUE TITLE
Http library SystemNet bug

### ISSUE THREAD

**Issue by oynomed** [openbullet/OpenBullet2#864] opened 2023-01-23 22:49 UTC
### Version of the software

0.2.5

### Operating system

Windows 10

### Browser / Native

Native

### What happened?

Choosing Http library SystemNet and unchecking Read Response Content, still give the full response code, see screenshot
https://i.imgur.com/OyYukFK.png

**Comment by openbullet** [comment] 2024-06-07 11:57
Duplicate of #754

**Closed by openbullet** 2024-06-07 11:57 UTC
Labels: bug
