### ISSUE TITLE
[Bug]: The operation was canceled.  

### ISSUE THREAD

**Issue by kix01** [openbullet/OpenBullet2#975] opened 2024-04-02 17:38 UTC
### Version of the software

0.2.5

### Operating system

Windows 11

### Browser / Native

Chrome

### What happened?

![Capture d'écran 2024-04-02 193620](https://github.com/openbullet/OpenBullet2/assets/138823490/c45ee17a-71ee-44c1-a385-ab228b93b6b7)
all bots are banned or have an error and when I go to "to chek" it shows me several error messages including him

**Comment by arshambh** [comment] 2024-04-21 04:54
Hello, please send your config here for testing....

**Comment by openbullet** [comment] 2024-06-06 16:52
It seems to be a proxy issue. Also there's not enough information to reproduce the issue, closing

**Closed** 2024-06-06 16:53 UTC
Labels: bug

**Comment by Goku001q** [comment] 2024-07-19 22:37
Hello admins of open bullet 2 , i am currently facing some problem in open bullet 2 native 0.2.5 when i extract file and open it it works fine but when i try to close it and reopen it it not reopen until i re-extract the file even if i restart my pc it's won't help and i am facing this problem from yesterday and other open bullet 2 version like 0.3.1 are opening and working good but the reason I don't want to use new version is new version have bug  - in hit output I can't add telegram api or even if i add it manually it's just vanish after i save settings that why i used to use 0.2.5 which was awesome thoo but it's now showing 0.2.5 lost in void did you guys just discontinued it? Due to some server error it's not reopening or something please if you are reading this reply me.

**Comment by openbullet** [comment] 2024-07-19 22:41
Hello @Goku001q 

Version 0.2.5 got automatically nuked by the CI/CD pipeline (because of some tag conflicts I assume) and we didn't bother reupping it since people should use the new version anyways.

Instead, what you should do is open a new GitHub issue for the problem you're facing with 0.3.1 (we cannot solve what we don't know about 😅 ), so that you can use the new version instead.

**Comment by Goku001q** [comment] 2024-07-19 22:47
So 0.2.5 version won't work anymore? As i already mentioned new 0.3.1 telegram hit output not working it's not taking telegram api even if i write it manually

**Comment by openbullet** [comment] 2024-07-19 22:55
> So 0.2.5 version won't work anymore? As i already mentioned new 0.3.1 telegram hit output not working it's not taking telegram api even if i write it manually

I'm saying that you cannot download version 0.2.5 (it still works if you have an old download, maybe yours is corrupted, sadly I don't have it and I cannot easily rebuild it). If you create an issue on GitHub, reporting the bug you're experiencing with version 0.3.1, I will make sure to fix it for version 0.3.2 so you can use that one. Please, open the issue and let's continue the conversation there to avoid spamming the people who commented on this (unrelated) issue, otherwise simply open a thread on the official forum https://discourse.openbullet.dev
