### ISSUE TITLE
Hits Sound not working....

### ISSUE THREAD

**Issue by Cyogenus** [openbullet/OpenBullet2#238] opened 2021-04-22 17:17 UTC
**Describe the bug**
When I get hits the hits sound doesn't go off. I have the hit sound enable check in settings. When I click the preview the hit sound.It works but when running a job and I get a hit I get no sound. Yes I have my volume up and the browser tap is unmuted. I'm using chrome browser and I also tested OB2 for the sound on Firefox and still when I get a hit I don't hear the rifle sound. I'm running windows 10 pro.

I also installed Ob2 on my laptop and still I don't hear the hit sound. 

If anyone reads this please take a moment of your time and enable the hit sound and see if it works for you or not please post in here.

This can't just be happening to me..

**Comment by NewBie-OBB** [comment] 2021-04-23 04:02
I often only use OBB on VPS so I don't care about sound hits :))

**Comment by openbullet** [comment] 2021-04-30 03:21
Are you on the specific job's page or on the job manager page when you get the hit? Because the sound only plays if you're currently on the specific job's page.

**Comment by Cyogenus** [comment] 2021-05-02 02:57
On the specific job page. Where it shows the hits on the config I'm using.

**Comment by openbullet** [comment] 2021-05-29 11:20
I'm closing this as I tested multiple times and cannot reproduce the issue. For future reference, when debugging it on Cyogenus' browser, it doesn't create the `<audio>` element for some reason, while other times it creates it. Calling `playHitSound()` manually from the console seems to work though. Please if anyone could provide more insight on this reopen the issue.

**Closed by openbullet** 2021-05-29 11:20 UTC
Labels: bug, low priority
