### ISSUE TITLE
[BUG] Error upon cloning Paused Job

### ISSUE THREAD

**Issue by Official-Husko** [openbullet/OpenBullet2#58] opened 2021-03-11 02:41 UTC
**Describe the bug**
If you pause a job and then try to clone it then it throws an error

**To Reproduce**
1. Go to 'Jobs'
2. Click on 'Clone on a Paused Job'
4. See error "An error has occurred. This application may no longer respond until reloaded. Reload"

**Expected behavior**
It should clone the Job without giving an error.

**Screenshots**
Should be pretty straight forward. Upon request i can send screenshots

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Firefox
 - Version: 86.0(64-bit)

**Comment by openbullet** [comment] 2021-03-11 03:11
Please press F12 and send the exception that you get in the javascript console, it will really help ^_^

**Comment by Official-Husko** [comment] 2021-03-11 16:29
> 
> 
> Please press F12 and send the exception that you get in the javascript console, it will really help ^_^

The Error that i receive on the console

```js
[2021-03-11T16:28:10.997Z] Error: System.NullReferenceException: Object reference not set to an instance of an object.

   at OpenBullet2.Shared.DataPoolSelector.<BuildRenderTree>b__0_31(RenderTreeBuilder __builder3) in C:\Users\scarf\source\repos\OpenBullet2\OpenBullet2\Shared\DataPoolSelector.razor:line 96

   at Microsoft.AspNetCore.Components.Forms.InputSelect`1.BuildRenderTree(RenderTreeBuilder builder)

   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)

   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)

   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue() blazor.server.js:21:24815
    log http://localhost:5000/_framework/blazor.server.js:21
    I http://localhost:5000/_framework/blazor.server.js:10
    C http://localhost:5000/_framework/blazor.server.js:10
    invokeClientMethod http://localhost:5000/_framework/blazor.server.js:1
    invokeClientMethod http://localhost:5000/_framework/blazor.server.js:1
    processIncomingData http://localhost:5000/_framework/blazor.server.js:1
    onreceive http://localhost:5000/_framework/blazor.server.js:1
    onmessage http://localhost:5000/_framework/blazor.server.js:1
```

**Comment by openbullet** [comment] 2021-03-16 01:56
This error doesn't seem related to cloning paused jobs, it's related to cloning that specific job in general.
As you can see the error you got refers to this line https://github.com/openbullet/OpenBullet2/blob/245683ffdf55e9a3641fee8de4eba2bc5b53b1bd/OpenBullet2/Shared/DataPoolSelector.razor#L96
It's clearly related to OB2 not being able to find the Wordlist Type, maybe you changed your Environment.ini file without removing a job which was using an old wordlist type that now is missing (my money's on that).
Anyways I'll close the issue as this is completely unrelated to cloning paused jobs as I cannot reproduce it.

**Closed by openbullet** 2021-03-16 01:56 UTC
Labels: bug
