### ISSUE TITLE
[Bug]: An error occurred using the connection to database 'main' on server

### ISSUE THREAD

**Issue by leakguard** [openbullet/OpenBullet2#772] opened 2022-07-22 11:20 UTC
### Version of the software

latest

### Operating system

Windows 10

### Browser / Native

Chrome

### What happened?

After running for a while, all checks go to To Check and then the program just stops working. And that's the message I get from the console.

`fail: Microsoft.EntityFrameworkCore.Database.Connection[20004]
      An error occurred using the connection to database 'main' on server '*\OpenBullet2\UserData\OpenBullet.db'.`

**Comment by openbullet** [comment] 2022-07-24 18:05
Looks like something is wrong with the database file. Make sure OB2 has permissions to write to that path, and try deleting the DB if the error persists to make it create a new one.

**Comment by openbullet** [comment] 2024-06-07 11:46
Unless this can be reliably reproduced on my end, I'm going to close this.

**Closed by openbullet** 2024-06-07 11:46 UTC
Labels: bug
