### ISSUE TITLE
[REQUEST] Flaresolverr integration for captcha

### ISSUE THREAD

**Issue by Gauvino** [openbullet/OpenBullet2#1002] opened 2024-07-01 20:44 UTC
**Is your feature request related to a problem? Please describe.**
Integrate https://github.com/FlareSolverr/FlareSolverr as proxy so every captcha could bypass or most of them.

**Comment by openbullet** [comment] 2024-07-01 20:46
Duplicate of #684

**Closed by openbullet** 2024-07-01 20:46 UTC
Labels: duplicate, enhancement
