### ISSUE TITLE
[REQUEST] RESTful API

### ISSUE THREAD

**Issue by vurezo** [openbullet/OpenBullet2#572] opened 2021-12-22 12:35 UTC
**Is your feature request related to a problem? Please describe.**
I need to query an API endpoint for my clients whilst using my proxies and CAPTCHA solving without exposing the underlying API endpoint to the client

**Describe the solution you'd like**
RESTful API for starting jobs, both batch jobs (where there'll be a final collection URL (i.e. will say "NOT READY" till job is complete) and a different URL that'll provide the current status and the output thus far) and "debugger" style single run jobs, whereby it'll stall the HTTP request till the job is finished and respond in the user's desired format.

**Describe alternatives you've considered**
Intermediate NPM script with REST API that uses OpenBullet 2 CLI.

**Additional context**
Ruri is <3

**Comment by openbullet** [comment] 2021-12-22 20:11
This is something I always intended to implement sooner or later.

**Comment by tcortega** [comment] 2022-01-01 13:17
> This is something I always intended to implement sooner or later.

😏😏😏

**Comment by AdaptCharm** [comment] 2022-04-30 20:05
The context provided by the op is somewhat unclear. Therefore, I've added a proposal of the API below.

# OB2 API
REST API that provides the option to share data and execute commands.

## Endpoint
- `/api` - The endpoint of the API.

## Routes
- `/jobs` - Get the status of all current jobs. Outputs the amount of hits, progress, cpm and status (idle/running)
- `/jobs/:controls` - Start, pause or stop all the jobs by passing a parameter (start/pause/stop)
- `/jobs/hits` - Get the hits data of all the jobs and output as json format
- `/job/:id` - Get the status of a specific job. Same output as the `/jobs/` route
- `/job/:id/:controls` - Start, pause or stop a specific job. Similar to the `/jobs/:controls` route
- `/job/:id/hits` - Get the hits data of a specific job. Same output as the `/jobs/hits` route

To access a route, send a request in this format: `[endpoint][route]`

## Authentication
A route can only be accessed if a valid `Authorization` header is present in the request headers. This can be:
- `Authorization: API_KEY` - Configurable on the `OB Settings` page. Used by default if no admin account.
- `Authorization: Basic BASE_64` - Where BASE_64 is USER:PASS encoded in base64 format.

## Note
The API can also be extended further by adding more routes.

If you have any route suggestions, feel free to share them below.

**Comment by vurezo** [comment] 2022-05-02 13:08
Me like, but get it done RURI @@@@

**Comment by AdaptCharm** [comment] 2022-12-03 11:00
@openbullet Any update on this?

**Comment by tcortega** [comment] 2022-12-03 15:37
> @openbullet Any update on this?

Ruri is a busy man and doesn't have much free time lately to go on and implement this. 
I can make an unnoficial api if people really need it, but back when I talked to him, he wanted to take care of this feature by himself.

And regarding the api's concerns, a few more routes would be required, such as an route to register proxies, proxy groups, another one to be able to tweak OB2's settings, and the list goes on...

**Comment by AdaptCharm** [comment] 2022-12-05 00:04
> > @openbullet Any update on this?
> 
> Ruri is a busy man and doesn't have much free time lately to go on and implement this. I can make an unnoficial api if people really need it, but back when I talked to him, he wanted to take care of this feature by himself.

If you could implement a functional API that would be great. Normally I would do it myself, but unfortunately I don't have much experience when it comes to C#.

I am confident this feature will be greatly appreciated by the OB2 community. I for one would appreciate it a lot, as it really opens a lot of new possibilities, which is currently not possible as of today.

> And regarding the api's concerns, a few more routes would be required, such as an route to register proxies, proxy groups, another one to be able to tweak OB2's settings, and the list goes on...

Essentially yes, there are some factors to consider when creating the API architecture.

What's important to remember is security and scalability. The API must be secure and able to support concurrent requests without impact on performance.

**Comment by openbullet** [comment] 2022-12-31 02:12
This feature is confirmed to be coming in 2023, so stay tuned. Sadly I cannot work at a fast pace because of my full time job, but I already started working on this so it is definitely coming.

**Comment by leohturbo** [comment] 2023-03-18 06:34
It's coming?

**Comment by leohturbo** [comment] 2023-03-18 06:34
@openbullet It's coming?

**Comment by openbullet** [comment] 2023-03-18 23:47
I am almost done with the API, but I will only release it after I rewrite the frontend client as well, moving away from Blazor in favor of a different SPA which will use the API. I will start working on the frontend next month. A temptative release date for this feature to be released is May 2023.

**Comment by hima101** [comment] 2023-05-26 01:58
any updates? are we close to get this feature?

**Comment by tcortega** [comment] 2023-05-26 13:52
> any updates? are we close to get this feature?

It's still work in progress and it will most likely take a while for ruri to finish the beta development of this. He is putting in some good hard work.

**Comment by pitagoras530** [comment] 2023-09-27 22:33
any news?

**Comment by mochomito** [comment] 2023-09-29 01:53
Nothing yet

Cartel de Sinaloa

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by giladspitzer** [comment] 2024-02-22 04:05
Any update on this?

**Comment by openbullet** [comment] 2024-03-28 06:57
The API is finished, I also completely rewrote the web client from scratch. It's on a private fork for now until everything is properly tested to make sure the release is stable.

Please be patient, sadly I can only develop OB2 as a hobby nowadays since I have a full time job.

**Comment by openbullet** [comment] 2024-06-10 06:58
The new client is going to be released soon and has a rich API so I'm going to close this, just wait for the release

**Closed by openbullet** 2024-06-10 06:59 UTC
Labels: enhancement
