### ISSUE TITLE
[Bug]: Monitor only works when in focus

### ISSUE THREAD

**Issue by Obegg** [openbullet/OpenBullet2#349] opened 2021-07-15 06:57 UTC
### Version of the software

0.1.20

### Operating system

Windows 10

### Browser

Google Chrome 91.0.4472.124 (Official Build) (64-bit)

### What happened?

Current behavior:
When a monitor for a job has been created - The actions of the same monitor job are executed only when in foreground
Meaning that actions won't be executed unless you manually navigate to the monitor tab

Expected behavior:
When a monitor for a job has been created - The actions of the same monitor job are executed always when in background
Meaning that actions will be executed at all times no matter where you navigate to

**Comment by openbullet** [comment] 2021-07-15 13:45
Tested and cannot reproduce. I coded the job monitor to trigger every second as a background task, so it doesn't matter if you're on the page or not, it will still trigger. Maybe yours is a refresh issue? Try using F5 to refresh the page see if that was the case.

**Comment by ObsessedHacker** [comment] 2021-07-15 14:17
> Tested and cannot reproduce. I coded the job monitor to trigger every second as a background task, so it doesn't matter if you're on the page or not, it will still trigger. Maybe yours is a refresh issue? Try using F5 to refresh the page see if that was the case.

Then try the following:
Open OB2
Open Browser
Create a monitor to start a job while idle
Close OB2
Open OB2 and at the same time open the browser on the jobs page
Observe results - job will not start (actions of the monitor)

**Comment by openbullet** [comment] 2021-07-15 14:34
If an action is not marked as repeatable and already has 1 execution it will not trigger again. Are you sure it didn't trigger before you closed OB2 and it already has 1 execution once you open it again?

**Comment by ObsessedHacker** [comment] 2021-07-15 15:01
Yes, I am sure.
Repeatable is turned on.

Active: ON
Repeatable: ON
Triggers: Job status Idle
Actions: Start Job 1

**Comment by openbullet** [comment] 2021-07-15 15:05
Okay I will check this

**Closed** 2022-12-03 13:19 UTC
Labels: bug
