### ISSUE TITLE
[Bug]: Very fast responses are not captured

### ISSUE THREAD

**Issue by DoneRetired** [openbullet/OpenBullet2#496] opened 2021-09-28 08:51 UTC
### Version of the software

0.1.25

### Operating system

Windows 10

### Browser / Native

Native / Browser

### What happened?

On certain API's (basically only possible local hosted) the response will be returned too fast for OpenBullet 2 to capture.

![image](https://user-images.githubusercontent.com/43043067/135055435-65b2e352-cb0b-4dff-94d5-6f0aaec48370.png)

This is using my AWS Signing api on my github. If you need something to test. I noticed it happens around the 1-15ms response area.

**Comment by AmyBergqvist** [comment] 2022-04-22 13:58
@DoneRetired Interesting! what do you mean by 'around the 1-15ms response area'?
If you mean the 'BOT ENDED AFTER 1-15ms' then i can never have that time, here it's ~250ms on several local web servers that i tested.
But if you meant 1-15ms response from the web server then i tried to reproduce it and always failed.

HOWEVER, It happens if the web-server returns no `Content-Length` or `Content-Length: 0` which isn't correct logically.
I assume you created web-server using `HttpListener` in .NET and not setting the `ctx.Response.ContentLength64 = pageBodyBytes.LongLength;`

While not sending `Content-Length` in response headers isn't logically correct if response body isn't empty, you can still set HTTP Library to `System.Net` to fix it in case you cannot fix your web-server.

**Comment by openbullet** [comment] 2022-04-23 13:44
My http client implementation in `RuriLib.Http` relies on the `Content-Length` from the webserver to know how big is the response body, so it makes sense that it skips reading it.

Thanks for the insight @AmyBergqvist, I didn't know about this behaviour of `HttpListener`!

I will close this since webservers that don't reply with a `Content-Length` should not be a thing.

In any case, if somebody stumbles across this issue in the future, try setting `SystemNet` as the HTTP library in the Http Request block, maybe that one will actually try to read the stream even without a `Content-Length` header and print the response.

**Closed by openbullet** 2022-04-23 13:44 UTC
Labels: bug, help wanted
