### ISSUE TITLE
[Bug]: Int/Float Variable on Requests

### ISSUE THREAD

**Issue by leakguard** [openbullet/OpenBullet2#383] opened 2021-08-03 00:21 UTC
### Version of the software

0.1.21

### Operating system

Windows 10

### Browser

Cent Browser

### What happened?

https://miniwebtool.com/modulo-calculator/?number1=1.737147E+10&number2=2147483647

It’s supposed to be 10413863035989 instead of 1.737147E+10.

**Comment by openbullet** [comment] 2021-12-26 14:27
Closing this as I think I fixed this. If it's not fixed, please reopen with a sample LoliCode to reproduce the error otherwise I don't think I understand exactly what you're doing to get the problem as the number you're using does not fit in an integer, and you shouldn't use a float either since it's not precise enough.

You can use a long if you need, just paste this in the LoliCode
```
long num = 10413863035989;

BLOCK:ConstantString
  value = $"The value is <num>"
  => VAR @myString
ENDBLOCK
```

**Closed by openbullet** 2021-12-26 14:27 UTC
Labels: bug
