### ISSUE TITLE
[BUG] A Few Bugs + [REQUEST] Auto Save Progress Occasionally

### ISSUE THREAD

**Issue by ObsessedHacker** [openbullet/OpenBullet2#143] opened 2021-03-19 08:19 UTC
**Short summary**
Bugs:
Slower.
Problems with job stopping and/or aborting:
1) Job is still running even when shown "idle", causing high CPU and memory usage).
2) "Skip" number issues.

REQUEST:
"Skip" number will be updated occasionally, without the need to stop the job.

_

**1) Slower checking after update 0.1.7**
Update 0.1.7 made the checking progress slower - the speed has significantly decreased and it takes longer to complete a job.
I've seen the changelog - "Optimized CPM calculation", and it's not a matter of "CPM calculation", it's a matter of slower checking.

**Expected behavior**
Faster Checking.

_

**2) NOT showing ALL Hits on "Data stats" - "Hits"**
Edit - Probably related to bug number 3.
The config outputs the Hits to Telegram (using HTTP request), but the Hits shown on Telegram doesn't match the ones on "Data stats" - "Hits".
Telegram hit output shows MORE Hits than "Data stats" - "Hits".
I've tried searching for the hits shown on Telegram, and it's not on "To Check" or "Custom", it's a ghost data that doesn't show up anywhere.
The problem is definitely NOT the config.
On top of that - Sometimes Telegram shows duplicated hits, but the wordlist does NOT have ANY duplicated data.
And those duplicated hits on Telegram, it happens 50% of the time, and not instantaneous.
For example: "X9" data posted to Telegram on 18:00 and after 7 minutes the same data "X9" posted again.
This bug is new with 0.1.7.
Note: Not using the "Hits output" - "Telegram Bot" of the job that's built-into the program since it outputs the "Custom" too, not just the Hits, also - Can't customize on what capture it outputs.
I'm guessing this bug is the reason why 0.1.7 is slower now.
It's probably related to bug number 3.

**To Reproduce**
1. Have a wordlist without any duplications.
2. Have a config with HTTP request to output hits to Telegram.
3. Start a job that you know will have more than 1 hit.
4. Stop the job after 1 hit output.
5. Start the same job again with "Skip" number to 0.
6. Stop the job after 1 hit output.
7. See Telegram, you have more than 2 hits (bug number 3 - probably because the previous job didn't stop)

**Expected behavior**
Stopping a job after clicking "Stop" or "Abort".
When job is shown "idle" it should be idle.

_

**3) High CPU and Memory Usage after stopping a job**
Stopping a job doesn't actually stop it apparently, task manager shows high CPU and memory usage, but the job is idle.
Is that why I get duplicated hits output? (Bug number 2) Seems like it can be explained this way that the job is still running on the background even though the job is shown to be idle.

**To Reproduce**
1. Start a job
2. Stop the job (and/or click "Abort")
3. Start the job from the start ("Skip" number should be 0).
4. Stop the job (and/or click "Abort")

**Expected behavior**
CPU and memory usage should be normal after stopping a job. 
Stopping a job after clicking "Stop" or "Abort".
When job is shown "idle" it should be idle.

_

**4) Stop a job = Multiply "Skip" Number**
When job is stopped the "Skip" number is being updated to double the "Progress" number.
If you progressed 100 then you skip 200, calculations is wrong.
Unless after each time you stop the job you edit the job, the incorrect number on "Skip" is shown.

**To Reproduce**
1. Start a job.
2. Stop the job after you progressed X amount (for example 100).
3. Start job again.
4. Stop the job after you progressed X amount (for example 100).
3. See "Other stats" - "Progress" and "Skip" Number.
4. "Skip" number has now doubled from the "progress" number shown..
5. Click on "Edit job" and see "Skip" number, it's the correct number.

Or Try this:
**To Reproduce**
1. Start a job.
2. Stop the job after you progressed X amount (for example 100).
3. Abort the job.
3. See "Other stats" - "Progress" and "Skip" Number.
4. "Skip" number has now doubled from the "progress" number shown..
5. Click on "Edit job" and see "Skip" number, it's the correct number.

**Expected behavior**
Skip number should be the same as the progressed number.

_

**5) Monitor" takes a long time to stop a job**
Monitor doesn't stop a job successfully, it does say "stopping" but doesn't stop.

**To Reproduce**
1. Start a job.
2. Click on 'Monitor'
3. Create new monitor
4. Try stopping and starting a job after "time elapsed" of 10 seconds (for example)
5. Check if job is stopped successfully (at least twice)

**Expected behavior**
Restarting a job successfully ALL the time.

_

Feature Suggestion:
Every once in a while the "Skip" number will be updated automatically, without the need to stop the job occasionally.

**Is your feature request related to a problem? Please describe.**
Yes. It's related to bug number 4 ("Stop a job = Multiply "Skip" Number") and bug number 5 ("Monitor" takes a long time to stop a job")
In order to prevent any data loss issues.

**Describe the solution you'd like**
Occasionally update the "Skip" number without stopping the job.
So in case of a random shut down you can continue from the same spot.
Job will be saved.

**Describe alternatives you've considered**
Creating a monitor job that will stop and start the job occasionally.

_

**Desktop:**
 - OS: Windows 10 - 64bit
 - Version 0.1.7

**Comment by RydjGit** [comment] 2021-03-19 10:50
- Please define high CPU Usage?
- Stoppiung the Job works perfectly in my testing.
- CPM perfromance is dependant on many variables (such as and not limited to: 
> Proxy quality
> Internet Bandwidth
> Complexity of config
> System resources

this is my testing just now V 0.1.7:
![CPM](https://user-images.githubusercontent.com/56438382/111768894-32ee5080-88b1-11eb-8d1e-8c41bf25a5f3.png)

other issues i leave to Auther to address.

I sugesset you run a new clean copy from the releases section and retest your results.

**Comment by ObsessedHacker** [comment] 2021-03-19 12:07
> * Please define high CPU Usage?
> * Stopping the Job works perfectly in my testing.
> * CPM perfromance is dependant on many variables (such as and not limited to:
> 
> > Proxy quality
> > Internet Bandwidth
> > Complexity of config
> > System resources
> 
> this is my testing just now V 0.1.7:
> ![CPM](https://user-images.githubusercontent.com/56438382/111768894-32ee5080-88b1-11eb-8d1e-8c41bf25a5f3.png)
> 
> other issues i leave to Auther to address.
> 
> I sugesset you run a new clean copy from the releases section and retest your results.

High CPU Usage = 90% Usage.

Already tried to run a new clean copy from the release section before reporting this bug.
There's some issues with stopping jobs.

I guess the reason why it was "slower" (bug number 1) was because the issue with the background job that was shown as "idle" (bug number 3)

What about the feature request?
Any opinions?

**Comment by openbullet** [comment] 2021-03-19 12:33
@ObsessedHacker please try on version 0.1.7 again and let us know if the issue with stopping jobs is still there

**Comment by openbullet** [comment] 2021-03-19 12:33
Also I would really like to know why people try to cram everything inside a single issue...

**Comment by ObsessedHacker** [comment] 2021-03-19 13:05
> @ObsessedHacker please try on version 0.1.7 again and let us know if the issue with stopping jobs is still there

Ok, so as per your request I tried using version 0.1.7 again from releases section and at first it it was working perfectly, no issues, then on the 26 repeated Executions it got stuck on stopping.
![image](https://user-images.githubusercontent.com/13978119/111784585-3dfeac00-88c4-11eb-988a-df4df43be41a.png)

I created a loop to test if I have issues:
![image](https://user-images.githubusercontent.com/13978119/111784655-52db3f80-88c4-11eb-993c-636bce9c453c.png)

**Comment by openbullet** [comment] 2021-03-19 13:07
@ObsessedHacker does it actually abort if you press abort manually? I can add the `Abort Job` action maybe that will help

**Comment by ObsessedHacker** [comment] 2021-03-19 13:10
> @ObsessedHacker does it actually abort if you press abort manually? I can add the `Abort Job` action maybe that will help

It does abort if I press "Abort" manually, yes.
But doing so will cause some tasks to be skipped on, right? since it doesn't finish processing the current tasks.

**Comment by openbullet** [comment] 2021-03-19 13:11
> 
> 
> > @ObsessedHacker does it actually abort if you press abort manually? I can add the `Abort Job` action maybe that will help
> 
> It does abort if I press "Abort" manually, yes.
> But doing so will cause some tasks to be skipped on, right? since it doesn't finish processing the current tasks.

That would be correct, but this is intended as a temporary fix while we figure out the actual problem that is causing it because it's going to take some time to properly debug.

**Comment by ObsessedHacker** [comment] 2021-03-19 13:14
> > > @ObsessedHacker does it actually abort if you press abort manually? I can add the `Abort Job` action maybe that will help
> > 
> > 
> > It does abort if I press "Abort" manually, yes.
> > But doing so will cause some tasks to be skipped on, right? since it doesn't finish processing the current tasks.
> 
> That would be correct, but this is intended as a temporary fix while we figure out the actual problem that is causing it because it's going to take some time to properly debug.

Ok then.

The only reason I'm even using "stop" or "abort" is to save the "skip" number.
So is it possible to implement a way to save it automatically as I suggested?

**Comment by openbullet** [comment] 2021-03-19 13:40
@ObsessedHacker I don't see why it wouldn't work as it is currently though. This is how it's done in the code, when you stop (or abort) the job it just increments the skip by the amount of data tested.
https://github.com/openbullet/OpenBullet2/blob/e32b61895b70d62ad37c2ba2a308345ee9582ac5/RuriLib/Models/Jobs/MultiRunJob.cs#L452
Maybe you're first clicking on stop and then on abort, hence increasing the skip by twice the amount tested?

**Comment by ObsessedHacker** [comment] 2021-03-19 14:21
> @ObsessedHacker I don't see why it wouldn't work as it is currently though. This is how it's done in the code, when you stop (or abort) the job it just increments the skip by the amount of data tested.
> https://github.com/openbullet/OpenBullet2/blob/e32b61895b70d62ad37c2ba2a308345ee9582ac5/RuriLib/Models/Jobs/MultiRunJob.cs#L452
> 
> 
> Maybe you're first clicking on stop and then on abort, hence increasing the skip by twice the amount tested?

No, it doesn't matter either when I click on "Stop" or "Abort", the result is the same,
Even when you create a monitor that will stop and start a job it does the same.
But it's just a matter of a display issue, it says it's gonna start at 2X but when you start it it's resuming normally as it should.
To test it - create a monitor for a job with the same settings shown on the screenshot and see the "Progress" number after each stop and each start changing.
"Progress" number will increase after a stop (double the amount of the tested), and will decrease (back to normal) after start.
It's working fine, just the number doesn't show the right amount.

But instead of stopping or aborting a job in order to save the skip number, is there any other way to save it?

**Comment by ObsessedHacker** [comment] 2021-03-19 21:04
> I cannot seem to reproduce your issue, when I click abort it looks like this on my build, but maybe it was because of my recent commits who knows.
> 
> ![immagine](https://user-images.githubusercontent.com/48930622/111798310-3c37e700-88ca-11eb-85d5-e51b9570c2ce.png)
> 
> Regarding the request:
> Currently the skip is updated in the database every time the record is updated, but this only happens if you're on the job details page of the UI currently. It needs to be moved to a background job inside the `MultiRunJob` class itself (or in the `JobManagerService`).
> 
> https://github.com/openbullet/OpenBullet2/blob/dc7cda7c06a0fcc0b6390eb05ea1d892671edf43/OpenBullet2/Shared/MultiRunJobViewer.razor.cs#L131
> 
> https://github.com/openbullet/OpenBullet2/blob/dc7cda7c06a0fcc0b6390eb05ea1d892671edf43/OpenBullet2/Shared/MultiRunJobViewer.razor.cs#L137

I agree, I think your recent commits might fixed it.

Regarding the request:
As I understand - Update 0.1.8 will bring this auto-save feature (I assume from the recent commits), only while you're on the job details page of the UI?
And future updates it will be moved to background?
Is that right?

**Comment by openbullet** [comment] 2021-03-19 21:07
@ObsessedHacker No, the auto-save is already added and working (we tested it before open beta) but only if you stay on the page. And yes, in the future I will move it to a dedicated background task so it will work even if you close the browser page.

**Comment by openbullet** [comment] 2021-03-29 12:58
I would like an update on these bugs on the latest version of the software please.

**Comment by openbullet** [comment] 2021-03-29 15:50
The fact that it doesn't stop the job is because it needs all of the current bots to finish with a status that is not BAN/ERROR/RETRY. So if you have a ban loop in your config (and no ban evasion set) for example due to some bad input data or some block giving an exception then it will never stop. That's the reason, it's not a bug. Anyways I'm going to close this one, if you experience more bugs please open new issues thanks ^_^

**Closed by openbullet** 2021-03-29 15:50 UTC
Labels: bug
